####################
# Comments
# 1. pods should be installed/updated
# 2. jazzy command should be running form framework root dir
####################
#names
module: VGSCheckout
title: VGSCheckoutSDK
author: Very Good Security
author_url: https://verygoodsecurity.com
github_url: https://github.com/verygoodsecurity/vgs-checkout-ios
github_file_prefix: https://github.com/verygoodsecurity/vgs-checkout-ios/tree/master
readme: README.md
#output folder
output: docs
#path to project
framework_root: ../
sdk: iphonesimulator
#settings
clean: true
objc: false
skip_undocumented: true
hide_documentation_coverage: true
theme: fullwidth
exclude:

custom_categories:
- name: VGSCheckout
  children:
  - VGSCheckout
  - VGSCheckoutDelegate
- name: Configuration
  children:
  - VGSCheckoutConfiguration
  - VGSCheckoutMultiplexingConfiguration
  - VGSCheckoutBasicConfigurationProtocol
  - VGSCheckoutDefaultTheme
- name: APIConfiguration
  children:
  - VGSCheckoutRequestOptions
  - VGSCheckoutRouteConfiguration
  - VGSCheckoutHTTPMethod
  - VGSCheckoutHostnamePolicy
  - VGSCheckoutDataMergePolicy
  - VGSCheckoutRequestResult
- name: PaymentCards
  children:
  - VGSCheckoutPaymentCards
  - VGSCheckoutPaymentCardModel
  - VGSCheckoutUnknownPaymentCardModel
  - VGSCheckoutCustomPaymentCardModel
- name: Debugging
  children:
  - VGSCheckoutLogger
  - VGSCheckoutLoggingConfiguration
