####################
# Comments
# 1. pods should be installed/updated
# 2. jazzy command should be running form framework root dir
####################
#names
module: VGSCheckoutSDK
title: VGSCheckoutSDK
author: Very Good Security
author_url: https://verygoodsecurity.com
github_url: https://github.com/verygoodsecurity/vgs-checkout-ios
github_file_prefix: https://github.com/verygoodsecurity/vgs-checkout-ios/tree/master
readme: README.md
#output folder
output: docs
#path to project
framework_root: ../
sdk: iphonesimulator
#settings
clean: true
objc: false
skip_undocumented: true
hide_documentation_coverage: true
theme: fullwidth
exclude:

custom_categories:
- name: VGSCheckout
  children:
  - VGSCheckout
  - VGSCheckoutDelegate
- name: Configuration
  children:
  - VGSCheckoutConfigurationProtocol
  - VGSCheckoutCustomConfiguration
  - VGSCheckoutFieldVisibility
  - VGSCheckoutBillingAddressVisibility
- name: Card Details Configuration
  children:
  - VGSCheckoutCardOptions
  - VGSCheckoutCardHolderOptions
  - VGSCheckoutCardNumberOptions
  - VGSCheckoutExpirationDateOptions
  - VGSCheckoutCardExpDateFormat
  - VGSCheckoutExpDateSeparateSerializer
  - VGSCheckoutCVCOptions
- name: Custom Billing Address Details Configuration
  children:
  - VGSCheckoutCustomBillingAddressOptions
  - VGSCheckoutCustomBillingAddressCountryOptions
  - VGSCheckoutCustomBillingAddressLine1Options
  - VGSCheckoutCustomBillingAddressLine2Options
  - VGSCheckoutCustomBillingAddressCityOptions
  - VGSCheckoutCustomBillingAddressPostalCodeOptions
- name: UITheme
  children:
  - VGSCheckoutDefaultTheme
  - VGSCheckoutThemeProtocol
  - VGSCheckoutTextFieldThemeProtocol
  - VGSCheckoutSubmitButtonThemeProtocol
  - VGSCheckoutViewThemeProtocol
- name: Form Validation Behaviour
  children:
  - VGSCheckoutFormValidationBehaviour
- name: APIConfiguration
  children:
  - VGSCheckoutCustomConfigurationRequestOptions
  - VGSCheckoutCustomRouteConfiguration
  - VGSCheckoutHTTPMethod
  - VGSCheckoutHostnamePolicy
  - VGSCheckoutDataMergePolicy
  - VGSCheckoutRequestResult
- name: Debugging
  children:
  - VGSCheckoutLogger
  - VGSCheckoutLoggingConfiguration
  - VGSCheckoutLogLevel
