# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

jobs:
  build-and-test-sdk-xcode13:
    macos:
      xcode: "13.0.0"
    steps:
      - checkout
      - run:
          name: Run Tests iOS 13-14
          command: >
            cd Tests/VGSCheckoutSDKTests/Resources/MockedData &&
            plutil -insert vaultID -string ${COLLECT_UNIT_TESTS_VAULT_ID} VGSCheckoutTestConfig.plist && cd .. && cd .. && cd .. && cd .. && ls && xcodebuild test -project VGSCheckoutSDK.xcodeproj -scheme VGSCheckoutSDKTests -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.0' -testPlan VGSCheckoutSDKTests
  build-and-test-sdk:
    macos:
      xcode: "12.5.1"
    steps:
      - checkout
      - run:
          name: Run Tests iOS 13-14
          command: >
            cd Tests/VGSCheckoutSDKTests/Resources/MockedData &&
            plutil -insert vaultID -string ${COLLECT_UNIT_TESTS_VAULT_ID} VGSCheckoutTestConfig.plist && cd .. && cd .. && cd .. && cd .. && ls && xcodebuild test -project VGSCheckoutSDK.xcodeproj -scheme VGSCheckoutSDKTests -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.5' -testPlan VGSCheckoutSDKTests
  build-and-ui-test-demo-app-ios-15:
    macos:
      xcode: "13.0.0"
    steps:
      - checkout
      - run:
          name: Run UI Tests
          command: >
            cd VGSCheckoutDemoApp/VGSCheckoutDemoApp/Models/MockedData &&
            plutil -insert vaultID -string ${COLLECT_UNIT_TESTS_VAULT_ID} UITestsMockedData.plist && cd .. && cd .. && cd .. && ls &&
            pod install &&
            xcrun instruments -w "iPhone 13 Pro Max (15.0) [" || true &&
            xcodebuild test -workspace VGSCheckoutDemoApp.xcworkspace
            -scheme VGSCheckoutDemoAppUITests
            -sdk iphonesimulator
            -destination 'platform=iOS Simulator,name=iPhone 13 Pro Max,OS=15.0'
  build-and-ui-test-demo-app-ios-13-14:
    macos:
      xcode: "12.5.1"
    steps:
      - checkout
      - run:
          name: Run UI Tests
          command: >
            cd VGSCheckoutDemoApp/VGSCheckoutDemoApp/Models/MockedData &&
            plutil -insert vaultID -string ${COLLECT_UNIT_TESTS_VAULT_ID} UITestsMockedData.plist && cd .. && cd .. && cd .. && ls &&
            pod install &&
            xcrun instruments -w "iPhone 12 (14.2) [" || true &&
            xcrun instruments -w "iPad Air (3rd generation) (13.7) [" || true &&
            xcodebuild test -workspace VGSCheckoutDemoApp.xcworkspace
            -scheme VGSCheckoutDemoAppUITests
            -sdk iphonesimulator
            -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.5'
            -destination 'platform=iOS Simulator,name=iPad Air (3rd generation),OS=13.7'


workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test-sdk-xcode13
      - build-and-test-sdk
      - build-and-ui-test-demo-app-ios-13-14
      - build-and-ui-test-demo-app-ios-15
