# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

jobs:
  build-and-test-sdk:
    macos:
      xcode: "12.1"
    steps:
      - checkout
      - run:
          name: Run Tests iOS 13-14
          command: >
            cd Tests/VGSCheckoutTests/Resources/MockedData &&
            plutil -insert vaultID -string ${COLLECT_UNIT_TESTS_VAULT_ID} VGSCheckoutTestConfig.plist && cd .. && cd .. && cd .. && xcodebuild test -project VGSCheckout.xcodeproj -scheme VGSCheckoutTests -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.2' -testPlan VGSCheckoutTests

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test-sdk

